ipfs/js-stores

- packages/interface-datastore/src/key.js
- packages/interface-datastore/test/key.spec.js
`instanceOf` is unreliable across EJS/CSM but also across different bundles loaded in the browser.
Add a `Key.asKey` method we can use as a more reliable `instanceOf` check.
> feat: add Key.asKey method

- .gitignore
- .npmrc
- README.md
- lerna.json
- package.json
- packages/interface-blockstore-tests/README.md
- packages/interface-blockstore-tests/package.json
- packages/interface-blockstore/README.md
- packages/interface-blockstore/package.json
- packages/interface-datastore-tests/README.md
- packages/interface-datastore-tests/package.json
- packages/interface-datastore/README.md
- packages/interface-datastore/package.json
- packages/interface-store/README.md
- packages/interface-store/package.json
Update project config to publish api docs
> docs: publish api docs

- packages/interface-blockstore-tests/src/index.ts
Store needs to be opened and closed.
> fix: open and close blockstore during interface tests

- .gitignore
- packages/interface-blockstore-tests/package.json
- packages/interface-blockstore-tests/src/index.ts
- packages/interface-blockstore/src/index.ts
- packages/interface-datastore-tests/package.json
- packages/interface-datastore-tests/src/index.ts
- packages/interface-datastore-tests/tsconfig.json
- packages/interface-datastore/src/index.ts
- packages/interface-store/src/index.ts
- Removes open/close from store as not every implementation needs them
- Removes query from store as it doesn't make sense for blockstores
- Removes batch from store as storing blocks in memory before writing is a bad idea
- Adds query/batch to datastore interface
- Adds getAll to blockstore interface
- Converts datastore tests to typescript
- Improves typing of datastore/blockstore tests to allow setup/teardown to recieve the right store type to open/close, etc
- Blockstore pair is now `{ cid, block }` instead of `{ key, value }`
BREAKING CHANGE: open/close/batch/query methods have been removed from store interface, query/batch added to datastore, getAll added to blockstore
> feat!: simplify store interface, move query/batch to datastore, add getAll to blockstore

- packages/interface-blockstore/src/index.ts
- packages/interface-datastore/src/index.ts
- packages/interface-store/src/index.ts
To allow for extra options like progress handlers, add generic types for extending the options types passed to the various store methods.
They are all defaulted to an empty interface (e.g. no extension) so this is a non-breaking change.
> feat: allow extending store method options

- packages/interface-datastore/src/index.ts
> fix: make datastore batch commit option extension optional

- packages/interface-blockstore-tests/src/index.ts
- packages/interface-datastore-tests/src/index.ts
- packages/interface-store/src/index.ts
To make the return value of getMany consistent with putMany and getAll, return a stream of pairs from the return type of getMany - this also allows decoupling of processing the output from the input since the output processor doesn't need any extra context since they get both the key and the value being returned.
BREAKING CHANGE: the output of store.getMany is now a stream of pairs
> fix!: return stream of pairs from getmany

- packages/interface-blockstore-tests/src/index.ts
- packages/interface-datastore-tests/src/index.ts
- packages/interface-store/src/index.ts
Otherwise if operating remotely we have the strange property of sending the data to be put once to the receiver and then again back to the sender.
> fix: return key from put and put many

- packages/blockstore-s3/src/index.ts
- packages/blockstore-s3/test/index.spec.ts
For consistency with blockstore-fs and to avoid problems with casing encode/decode all CID keys as base32upper
BREAKING CHANGE: s3 filenames are now all base32upper
> fix!: encode/decode blockstore-s3 keys in base32upper

- packages/blockstore-s3/src/index.ts
- packages/blockstore-s3/src/sharding.ts
- packages/blockstore-s3/test/index.spec.ts
To avoid non-obvious performance footguns shard by default
> fix: add sharding to s3 blockstore

- packages/interface-blockstore/README.md
- packages/interface-datastore/README.md
The links in the Datastore interface were out of date.
Took the opportunity to add an implementation list to the Blockstore interface while I was at it.
> docs: Update Blockstore and Datastore implementation lists

- packages/blockstore-core/README.md
- packages/blockstore-core/package.json
- packages/blockstore-core/src/black-hole.ts
- packages/datastore-core/README.md
- packages/datastore-core/package.json
- packages/datastore-core/src/black-hole.ts
Sometimes it's useful to not store anything, for example calculating the CID of a datastructure without actually storing any of the data.
> feat: add black hole stores

- packages/interface-blockstore/src/index.ts
- packages/interface-datastore/src/index.ts
- packages/interface-store/src/index.ts
To make the type opt-in restore the empty object, otherwise extending classes become very verbose.
> fix: restore empty object default

- packages/datastore-fs/README.md
This PR fixes the capitalization of the import of `FsDatastore` in the readme.
> docs: fix capitalization in readme of datastore-fs.

- packages/blockstore-core/README.md
- packages/blockstore-core/package.json
- packages/blockstore-core/src/index.ts
- packages/blockstore-core/src/tiered.ts
- packages/blockstore-core/test/tiered.spec.ts
To enable use cases where blocks may be stored in more than one location, add a `TieredBlockstore` class to `blockstore-core` similar to the`TieredDatastore` class found in `datastore-core`.
> feat: add tiered blockstore

- packages/blockstore-s3/package.json
- packages/datastore-s3/package.json
Currently, `datastore-s3` and `blockstore-s3` cannot be used due to incorrect export path.
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'node_modules/datastore-s3/src/index.js'
```
> fix: incorrect export path

- packages/blockstore-core/test/tiered.spec.ts
- packages/blockstore-fs/src/index.ts
- packages/blockstore-idb/src/index.ts
- packages/blockstore-level/src/index.ts
- packages/blockstore-level/test/node.ts
- packages/blockstore-s3/README.md
- packages/blockstore-s3/examples/helia/README.md
- packages/blockstore-s3/examples/helia/index.js
- packages/blockstore-s3/examples/helia/package.json
- packages/blockstore-s3/package.json
- packages/blockstore-s3/src/index.ts
- packages/blockstore-s3/test/utils/s3-mock.ts
- packages/datastore-idb/src/index.ts
- packages/datastore-s3/README.md
- packages/datastore-s3/src/index.ts
Docs code comments and specs refer to datastores within blockstore packages.
Theres also as small change to an error and exported type https://github.com/ipfs/js-stores/commit/e3302b697c97db7f8add70bb1ab9530cfa7ff928
> fix: cleanup references to datastore in blockstores

- packages/interface-datastore/package.json
- packages/interface-datastore/src/key.ts
The `Key.random` function isn't used anywhere in libp2p/helia so use a simpler key generation function that works with react-native.
> fix: remove nanoid

- packages/blockstore-core/README.md
- packages/blockstore-core/package.json
- packages/blockstore-core/src/base.ts
- packages/blockstore-core/src/identity.ts
- packages/blockstore-core/src/index.ts
- packages/blockstore-core/test/identity.spec.ts
- packages/blockstore-core/typedoc.json
Add a blockstore implementation that supports identity CIDs.
> feat: add identity blockstore

- packages/datastore-core/src/namespace.ts
- packages/datastore-core/test/namespace.spec.ts
This PR stops the error that the namespaced datastore throws when queried, see #236 for reproduction.
Fixes: #236
> fix: stop namespaced datastore throwing when queried

- packages/blockstore-core/package.json
- packages/blockstore-core/src/identity.ts
- packages/blockstore-core/test/identity.spec.ts
Allow passing a child blockstore to an identity blockstore.
> fix: identity blockstore should wrap child

- package.json
The latest version of aegir ships with semantic-release-monorepo which should be run in each package, not the root.
> fix: run release in each package

- packages/blockstore-fs/package.json
- packages/blockstore-fs/src/index.ts
- packages/datastore-fs/package.json
- packages/datastore-fs/src/index.ts
fixes #284
fast-write-atomic hasn't been updated in 5 years, is CJS, and is slower than steno (updated 2 months ago).
Benchmarks for various content-types & libraries (though we only use Uint8Arrays) can be found at https://github.com/SgtPooki/fast-write-atomic#benchmarks
However, there may be further room for improvement by moving to [fs.createWriteStream](https://nodejs.org/api/fs.html#fscreatewritestreampath-options)
```
╰─ ✔ ❯ hyperfine --parameter-list branch 284-chore-replace-fast-write-atomic-with-steno,main --setup "git switch {branch} && npm run reset && npm i && npm run build" --runs 20  -w 1 "npm run test:node"
Benchmark 1: npm run test:node (branch = 284-chore-replace-fast-write-atomic-with-steno)
Time (mean ± σ):     27.212 s ±  0.832 s    [User: 34.810 s, System: 6.051 s] …
```
> fix: replace fast-atomic-write with steno

- packages/interface-store/src/errors.ts
Give errors both `.name` and `.code` properties for better compatibility.
> fix: restore code property
